"""
Shared utilities and models for 2-Aside Platform
"""

__version__ = "1.0.0"

# Export commonly used modules for easy imports
from .database import Base, SessionLocal, get_db, engine
from .models import (
    User,
    Wallet,
    BankDetails,
    WalletLog,
    ReferralReward,
    Game,
    BetRegistration,
    BetQueue,
    MatchPair,
    FundingRequest,
    WithdrawalRequest,
    FundingMatchPair,
    MergeCycle,
    AdminWallet,
)

# Create aliases for common naming conventions
Transaction = WalletLog  # Transaction is an alias for WalletLog
FundingMatch = MatchPair  # FundingMatch is an alias for MatchPair
from .auth import (
    hash_password,
    verify_password,
    create_access_token,
    create_refresh_token,
    verify_refresh_token,
    decode_access_token,
    get_current_user_id,
    get_current_user,
    require_admin,
)
from .schemas import (
    RegisterRequest,
    LoginRequest,
    TokenResponse,
    RefreshTokenRequest,
    UserResponse,
    UpdateUserRequest,
    ChangePasswordRequest,
    WalletResponse,
    BalanceResponse,
    SwitchCurrencyRequest,
    TransactionResponse,
    BetResponse,
    GameResponse,
    FundingRequestCreate,
    WithdrawalRequestCreate,
    FundingMatchResponse,
    SuccessResponse,
    ErrorResponse,
    PaginatedResponse,
    PaginationMeta,
)
from .exceptions import (
    TwoAsideBaseException,
    AuthenticationError,
    InvalidCredentialsError,
    InvalidTokenError,
    TokenExpiredError,
    MissingTokenError,
    AuthorizationError,
    AccountBlockedError,
    ValidationError,
    InvalidReferralCodeError,
    InvalidAmountError,
    InvalidCurrencyError,
    BusinessLogicError,
    InsufficientBalanceError,
    DuplicateRegistrationError,
    BettingClosedError,
    SelfReferralError,
    FundingNotMatchedError,
    ProofAlreadyUploadedError,
    ProofNotUploadedError,
    ResourceNotFoundError,
    UserNotFoundError,
    WalletNotFoundError,
    FundingRequestNotFoundError,
)
from .constants import (
    PLATFORM_FEE_PERCENTAGE,
    REFERRAL_BONUS_PERCENTAGE,
    MIN_BET_AMOUNT,
    MAX_BET_AMOUNT,
    MIN_FUNDING_AMOUNT,
    MAX_FUNDING_AMOUNT,
    MIN_WITHDRAWAL_AMOUNT,
    MAX_WITHDRAWAL_AMOUNT,
    FUNDING_REQUEST_EXPIRATION_HOURS,
    WITHDRAWAL_REQUEST_EXPIRATION_HOURS,
    CurrencyType,
    BetSide,
    BetType,
    BetStatus,
    GameStatus,
    FundingRequestStatus,
    WithdrawalRequestStatus,
    FundingMatchStatus,
    TransactionType,
)
from .utils import (
    round_decimal,
    format_currency,
    calculate_platform_fee,
    calculate_user_payout,
    calculate_1v1_payout,
    calculate_rendezvous_share,
    generate_referral_code,
    validate_referral_code,
    calculate_pagination,
    get_offset_limit,
    generate_transaction_reference,
)

__all__ = [
    # Database
    "Base",
    "SessionLocal",
    "get_db",
    "engine",
    # Models
    "User",
    "Wallet",
    "BankDetails",
    "WalletLog",
    "Transaction",  # Alias for WalletLog
    "ReferralReward",
    "Game",
    "BetRegistration",
    "BetQueue",
    "MatchPair",
    "FundingMatch",  # Alias for MatchPair
    "FundingRequest",
    "WithdrawalRequest",
    # Auth
    "hash_password",
    "verify_password",
    "create_access_token",
    "create_refresh_token",
    "verify_refresh_token",
    "decode_access_token",
    "get_current_user_id",
    "get_current_user",
    "require_admin",
    # Schemas
    "RegisterRequest",
    "LoginRequest",
    "TokenResponse",
    "RefreshTokenRequest",
    "UserResponse",
    "UpdateUserRequest",
    "ChangePasswordRequest",
    "WalletResponse",
    "BalanceResponse",
    "SwitchCurrencyRequest",
    "TransactionResponse",
    "BetResponse",
    "GameResponse",
    "FundingRequestCreate",
    "WithdrawalRequestCreate",
    "FundingMatchResponse",
    "SuccessResponse",
    "ErrorResponse",
    "PaginatedResponse",
    "PaginationMeta",
    # Exceptions
    "TwoAsideBaseException",
    "AuthenticationError",
    "InvalidCredentialsError",
    "InvalidTokenError",
    "TokenExpiredError",
    "MissingTokenError",
    "AuthorizationError",
    "AccountBlockedError",
    "ValidationError",
    "InvalidReferralCodeError",
    "InvalidAmountError",
    "InvalidCurrencyError",
    "BusinessLogicError",
    "InsufficientBalanceError",
    "DuplicateRegistrationError",
    "BettingClosedError",
    "SelfReferralError",
    "FundingNotMatchedError",
    "ProofAlreadyUploadedError",
    "ProofNotUploadedError",
    "ResourceNotFoundError",
    "UserNotFoundError",
    "WalletNotFoundError",
    "FundingRequestNotFoundError",
    # Constants
    "PLATFORM_FEE_PERCENTAGE",
    "REFERRAL_BONUS_PERCENTAGE",
    "MIN_BET_AMOUNT",
    "MAX_BET_AMOUNT",
    "MIN_FUNDING_AMOUNT",
    "MAX_FUNDING_AMOUNT",
    "MIN_WITHDRAWAL_AMOUNT",
    "MAX_WITHDRAWAL_AMOUNT",
    "FUNDING_REQUEST_EXPIRATION_HOURS",
    "WITHDRAWAL_REQUEST_EXPIRATION_HOURS",
    "CurrencyType",
    "BetSide",
    "BetType",
    "BetStatus",
    "GameStatus",
    "FundingRequestStatus",
    "WithdrawalRequestStatus",
    "FundingMatchStatus",
    "TransactionType",
    # Utils
    "round_decimal",
    "format_currency",
    "calculate_platform_fee",
    "calculate_user_payout",
    "calculate_1v1_payout",
    "calculate_rendezvous_share",
    "generate_referral_code",
    "validate_referral_code",
    "calculate_pagination",
    "get_offset_limit",
    "generate_transaction_reference",
]
